export interface WireProduct {
  slug: string;
  name: string;
  img: string;
  tags: string[];
  category: string;
  voltage: string;
  desc: string;
  description: string[];
  usage: string[];
  features: string[];
}

export const wireProducts: WireProduct[] = [
  {
    slug: "thhn-thwn-2-copper",
    name: "THHN / THWN-2 Copper",
    img: "/assets/wires_thhn.jpg",
    tags: ["600V", "DRY/DAMP"],
    category: "Building Wire",
    voltage: "600V",
    desc: "General purpose building wire for services, feeders, and branch circuits in commercial and industrial applications.",
    description: [
      "THHN/THWN-2 is the most widely used building wire in commercial and industrial construction. This dual-rated conductor features a thermoplastic PVC insulation with a nylon jacket, providing exceptional resistance to moisture, heat, and mechanical damage.",
      "Rated for 600 volts and temperatures up to 90°C in dry locations and 75°C in wet locations, THHN/THWN-2 wire meets or exceeds the requirements of UL 83 and Federal Specification J-C-30B. Available in solid and stranded configurations from 14 AWG through 1000 kcmil.",
    ],
    usage: [
      "Commercial building wiring in conduit and raceways",
      "Industrial feeders and branch circuits",
      "Service entrance conductors",
      "Machine tool wiring",
      "Control circuit wiring in panels",
    ],
    features: [
      "Dual-rated THHN/THWN-2 for maximum versatility",
      "PVC insulation with nylon jacket for abrasion resistance",
      "90°C dry / 75°C wet temperature rating",
      "Available in solid and stranded copper conductors",
      "UL Listed and CSA certified",
      "Color-coded insulation per NEC requirements",
    ],
  },
  {
    slug: "xhhw-2-copper",
    name: "XHHW-2 Copper",
    img: "/assets/wires_xhhw2.jpg",
    tags: ["600V", "90°C WET/DRY"],
    category: "Building Wire",
    voltage: "600V",
    desc: "Thermoset insulated wire offering superior resistance to abrasion, moisture, and heat. Ideal for harsh industrial environments.",
    description: [
      "XHHW-2 copper wire features cross-linked polyethylene (XLPE) thermoset insulation, delivering superior performance in the most demanding industrial environments. Unlike thermoplastic insulations, the cross-linked molecular structure provides exceptional resistance to heat deformation, chemical exposure, and mechanical stress.",
      "Rated at 90°C in both wet and dry locations at 600V, XHHW-2 maintains its full ampacity rating regardless of installation environment — a significant advantage over THHN/THWN-2 in wet applications. This makes it the preferred choice for underground feeders, cable tray installations, and chemical processing facilities.",
    ],
    usage: [
      "Industrial power distribution in harsh environments",
      "Underground feeder circuits and direct burial (in conduit)",
      "Cable tray installations",
      "Chemical and petrochemical processing plants",
      "Wet and corrosive location wiring",
    ],
    features: [
      "Cross-linked polyethylene (XLPE) thermoset insulation",
      "90°C rating in both wet and dry locations",
      "Superior chemical and moisture resistance",
      "Excellent abrasion and cut-through resistance",
      "Full ampacity maintained in wet environments",
      "Sunlight resistant for outdoor installations",
    ],
  },
  {
    slug: "tray-cable-tc",
    name: "Tray Cable (TC)",
    img: "/assets/wires_tc.jpg",
    tags: ["600V", "TC-ER RATED"],
    category: "Tray Cable",
    voltage: "600V",
    desc: "Multi-conductor power and control cables designed for use in cable trays, raceways, and outdoor locations supported by a messenger wire.",
    description: [
      "Type TC (Tray Cable) is a versatile multi-conductor cable engineered specifically for industrial cable tray systems, raceways, and messenger-supported outdoor installations. Featuring individually insulated conductors with an overall PVC jacket, TC cables deliver reliable power, lighting, and control circuit performance in demanding industrial settings.",
      "Our TC-ER (Exposed Run) rated cables meet the enhanced requirements of NEC Article 336, allowing installation in exposed runs between cable trays and equipment without additional support or protection — significantly reducing installation time and material costs in industrial facilities.",
    ],
    usage: [
      "Industrial cable tray power distribution",
      "Control and signal circuits in manufacturing",
      "Exposed runs between trays and equipment (TC-ER)",
      "Outdoor messenger-supported installations",
      "Automated production line wiring",
    ],
    features: [
      "TC-ER rated for exposed run installations",
      "Multi-conductor configurations (2-37 conductors)",
      "Sunlight and oil resistant PVC outer jacket",
      "Individual conductor insulation color-coded",
      "Available with ground conductor",
      "Meets NEC Article 336 and UL 1277",
    ],
  },
  {
    slug: "soow-portable-cord",
    name: "SOOW Portable Cord",
    img: "/assets/wires_soow.jpg",
    tags: ["600V", "FLEXIBLE"],
    category: "Portable Cord",
    voltage: "600V",
    desc: "Service cord with an oil-resistant thermoset jacket. Engineered for heavy-duty applications where flexibility and durability are paramount.",
    description: [
      "SOOW (Service, Oil-resistant, Oil-resistant jacket, Weather-resistant) portable cord is the industry standard for heavy-duty temporary and semi-permanent power connections. Featuring finely stranded copper conductors with thermoset rubber insulation and an oil-resistant thermoset outer jacket, SOOW cord delivers exceptional flexibility even in extreme cold conditions.",
      "Rated at 600V and designed for extra-hard usage per NEC Article 400, SOOW cord withstands repeated coiling, heavy foot traffic, and exposure to oils, chemicals, and UV radiation. It is the preferred choice for industrial portable equipment, construction tools, and stage/entertainment power distribution.",
    ],
    usage: [
      "Portable industrial equipment and tools",
      "Construction site temporary power",
      "Stage and entertainment lighting/sound",
      "Motor leads and portable machinery",
      "Marine shore power connections",
    ],
    features: [
      "Extra-hard service (600V) rating",
      "Oil-resistant thermoset rubber jacket",
      "Highly flexible in temperatures as low as -40°C",
      "Weather and UV resistant for outdoor use",
      "Finely stranded copper conductors",
      "Available in 2-6 conductor configurations",
    ],
  },
  {
    slug: "nm-b-romex-building-wire",
    name: "NM-B (Romex) Building Wire",
    img: "/assets/wires_nmb.png",
    tags: ["600V", "RESIDENTIAL"],
    category: "Building Wire",
    voltage: "600V",
    desc: "Non-metallic sheathed cable for residential branch circuits. The standard for interior wiring in homes and light commercial buildings.",
    description: [
      "Type NM-B (Non-Metallic Sheathed Cable), commonly referred to by the brand name Romex, is the standard residential branch circuit wiring used throughout North America. Featuring individually insulated copper conductors and a bare grounding wire bundled within a flame-retardant PVC outer jacket, NM-B cable provides safe, efficient power distribution for interior building applications.",
      "Rated at 600V with a 90°C conductor temperature rating, NM-B cable is designed for installation in normally dry interior locations — walls, ceilings, floors, and attics. Available in common configurations from 14/2 through 6/3 with ground, NM-B cable meets the requirements of NEC Article 334 and UL 719.",
    ],
    usage: [
      "Residential branch circuit wiring (15A, 20A, 30A circuits)",
      "Interior wall, ceiling, and floor installations",
      "Lighting circuits in homes and apartments",
      "Outlet and receptacle circuits",
      "Light commercial interior wiring",
    ],
    features: [
      "Flame-retardant PVC outer jacket",
      "90°C rated copper conductors",
      "Includes bare copper grounding conductor",
      "Color-coded outer jacket by gauge (white=14AWG, yellow=12AWG, orange=10AWG)",
      "Sequential footage markings for easy measurement",
      "UL Listed per NEC Article 334",
    ],
  },
  {
    slug: "mc-metal-clad-cable",
    name: "MC Metal-Clad Cable",
    img: "/assets/wires_mc.png",
    tags: ["600V", "ARMORED"],
    category: "Armored",
    voltage: "600V",
    desc: "Factory-assembled cable with flexible interlocked metal armor providing superior mechanical protection for commercial installations.",
    description: [
      "Type MC (Metal-Clad) Cable is a factory-assembled cable featuring insulated conductors enclosed in a flexible, spiraling interlocked metal armor — typically aluminum or galvanized steel. This construction provides superior mechanical protection, electromagnetic interference (EMI) shielding, and eliminates the need for separate conduit in many commercial and industrial installations.",
      "MC cable is permitted for use in nearly all commercial and industrial environments, including cable trays, direct burial (when jacketed), and exposed or concealed locations. The interlocked armor design allows flexible routing around obstacles while maintaining robust physical protection, making it the preferred choice for commercial office buildings, hospitals, and data centers.",
    ],
    usage: [
      "Commercial building power distribution",
      "Hospital and healthcare facility wiring",
      "Data center power feeds",
      "Industrial exposed-run installations",
      "Cable tray and raceway installations",
    ],
    features: [
      "Interlocked aluminum or steel armor",
      "Superior mechanical and crush protection",
      "EMI/RFI shielding capability",
      "Eliminates need for separate conduit",
      "Available with PVC jacket for wet locations",
      "Meets NEC Article 330 and UL 1569",
    ],
  },
  {
    slug: "ser-service-entrance-cable",
    name: "SER Service Entrance Cable",
    img: "/assets/wires_ser.png",
    tags: ["600V", "SERVICE"],
    category: "Service",
    voltage: "600V",
    desc: "Round service entrance cable with individually insulated conductors and bare ground, designed for feeder and sub-panel connections.",
    description: [
      "Type SER (Service Entrance, Round) cable is a multi-conductor cable specifically designed for service entrance applications, feeder circuits, and branch circuits. Featuring individually insulated XHHW-2 rated conductors with a bare copper grounding conductor, all wrapped in a grey flame-retardant PVC outer jacket, SER cable delivers reliable power from the service disconnect to sub-panels and heavy-duty appliance circuits.",
      "SER cable's round cross-section and included grounding conductor make it the preferred choice for applications downstream of the service disconnect — feeder runs to sub-panels, electric range circuits, dryer circuits, and HVAC equipment connections. Available in aluminum and copper configurations from 6 AWG through 4/0 AWG.",
    ],
    usage: [
      "Feeder circuits from main panel to sub-panels",
      "Electric range and oven connections",
      "Clothes dryer circuits",
      "HVAC equipment power feeds",
      "Above-ground service entrance runs",
    ],
    features: [
      "XHHW-2 rated individual conductor insulation",
      "Includes bare copper grounding conductor",
      "Flame-retardant and sunlight resistant PVC jacket",
      "Available in copper and aluminum",
      "Suitable for interior and exterior above-ground use",
      "Meets NEC Article 338 and UL 854",
    ],
  },
  {
    slug: "welding-cable",
    name: "Welding Cable",
    img: "/assets/wires_welding.png",
    tags: ["600V", "HEAVY-DUTY"],
    category: "Portable Cord",
    voltage: "600V",
    desc: "Ultra-flexible, finely stranded copper cable for arc welding power leads and heavy-duty portable power applications.",
    description: [
      "Welding cable is a single-conductor cable designed specifically for the secondary circuits of electric welding equipment. Featuring an extremely fine-stranded copper conductor (up to Class K stranding) with a durable EPDM or neoprene thermoset rubber insulation, welding cable delivers the maximum flexibility required for manual welding operations while handling extremely high currents.",
      "Rated at 600V and designed to withstand the harsh conditions of welding environments — including heat, oil, weld splatter, abrasion, and repeated flexing — welding cable is also widely used for battery connections, power supply leads, and other applications requiring extreme flexibility and high current capacity.",
    ],
    usage: [
      "Arc welding machine secondary circuits",
      "Resistance welding power leads",
      "Battery bank interconnections",
      "Portable power distribution",
      "Grounding cables for welding operations",
    ],
    features: [
      "Ultra-fine stranded copper (Class K) for maximum flexibility",
      "EPDM or neoprene thermoset rubber insulation",
      "Resistant to oil, weld splatter, and chemicals",
      "Remains flexible in temperatures as low as -50°C",
      "High current capacity with low voltage drop",
      "Available from 6 AWG through 500 kcmil",
    ],
  },
  {
    slug: "hv-tray-cable-15kv",
    name: "HV Tray Cable (15kV)",
    img: "/assets/wires_hv_tc.jpg",
    tags: ["15kV", "XLPE/PVC"],
    category: "Tray Cable",
    voltage: "15kV",
    desc: "Medium voltage tray cable with XLPE insulation and PVC jacket for high-power industrial distribution and utility feeder applications.",
    description: [
      "High-Voltage Tray Cable (HV-TC) is a medium voltage power cable rated at 15kV, designed for critical power distribution in industrial facilities, utility substations, and large-scale commercial buildings. Featuring cross-linked polyethylene (XLPE) insulation with a PVC outer jacket, HV-TC cables deliver reliable performance in cable tray systems where medium voltage power must be distributed across large facilities.",
      "Our HV-TC cables are constructed with multiple individually shielded copper conductors, each featuring a semi-conducting conductor shield, XLPE insulation, semi-conducting insulation shield, and copper tape shield — providing exceptional dielectric performance and fault current handling capability up to 500 kcmil per phase.",
    ],
    usage: [
      "Industrial medium voltage power distribution",
      "Utility substation feeder circuits",
      "Large commercial building main feeds",
      "Mining and heavy manufacturing power systems",
      "Renewable energy plant collection circuits",
    ],
    features: [
      "15kV rated with 133% insulation level",
      "XLPE insulation with PVC overall jacket",
      "Copper tape shielding on each conductor",
      "Semi-conducting conductor and insulation shields",
      "Available up to 3×500 kcmil copper",
      "Sunlight resistant and suitable for cable tray",
    ],
  },
  {
    slug: "sjoow-portable-cord",
    name: "SJOOW Portable Cord",
    img: "/assets/wires_sjoow.jpg",
    tags: ["300V", "WATER RESISTANT"],
    category: "Portable Cord",
    voltage: "300V",
    desc: "Junior service oil-resistant portable cord for light-to-medium duty applications. Water resistant for damp and wet environments.",
    description: [
      "SJOOW (Service Junior, Oil-resistant, Oil-resistant jacket, Weather-resistant) portable cord is a versatile, durable cable designed for light-to-medium duty portable power applications. With a 300V rating and oil-resistant thermoset rubber insulation, SJOOW cord is an excellent choice for power tools, kitchen equipment, portable lighting, and other appliances operating at lower voltages.",
      "The weather-resistant jacket and water-resistant construction make SJOOW cord suitable for both indoor and outdoor use in damp or wet environments. Its finely stranded copper conductors provide excellent flexibility for repeated handling and coiling, while the rugged thermoset jacket resists abrasion, oil, and chemicals.",
    ],
    usage: [
      "Portable power tools and small equipment",
      "Commercial kitchen and food service equipment",
      "Outdoor portable lighting",
      "Agricultural equipment power cords",
      "Temporary event and entertainment power",
    ],
    features: [
      "300V hard service junior rating",
      "Oil-resistant thermoset rubber insulation and jacket",
      "Water resistant for damp/wet locations",
      "Weather and UV resistant for outdoor use",
      "Flexible fine-stranded copper conductors",
      "Available in 18 AWG through 10 AWG",
    ],
  },
  {
    slug: "tew-mtw-machine-wire",
    name: "TEW/MTW Machine Tool Wire",
    img: "/assets/wires_tew_mtw.jpg",
    tags: ["600V", "105°C"],
    category: "Building Wire",
    voltage: "600V",
    desc: "Thermoplastic insulated machine tool wire rated for 105°C. Designed for internal wiring of appliances, control panels, and machinery.",
    description: [
      "TEW/MTW (Thermoplastic Equipment Wire / Machine Tool Wire) is a single-conductor wire specifically designed for the internal wiring of appliances, machine tools, control panels, and similar equipment. Rated at 600V with a 105°C temperature rating, TEW/MTW wire provides reliable performance in the elevated temperature environments typically found inside electrical enclosures and machinery.",
      "Featuring a PVC insulation with enhanced thermal properties, TEW/MTW wire meets the requirements of both UL 1063 (Machine Tool Wiring) and CSA C22.2 standards. Available in a wide range of gauges and colors, this wire is the go-to choice for OEM equipment manufacturers and panel builders across North America.",
    ],
    usage: [
      "Machine tool and CNC equipment internal wiring",
      "Control panel and switchgear wiring",
      "Appliance manufacturing internal connections",
      "Industrial automation cabinet wiring",
      "Motor control center (MCC) wiring",
    ],
    features: [
      "105°C temperature rating for enclosed environments",
      "600V voltage rating",
      "PVC insulation with enhanced thermal stability",
      "Dual rated TEW/MTW for cross-border compliance",
      "Available in 22 AWG through 2/0 AWG",
      "Extensive color selection for circuit identification",
    ],
  },
  {
    slug: "braided-shielded-cable",
    name: "Braided Shielded Cable",
    img: "/assets/wires_braided.png",
    tags: ["600V", "EMI SHIELDED"],
    category: "Shielded",
    voltage: "600V",
    desc: "Tinned copper braided shield cable for noise-sensitive circuits. Essential for instrumentation, data, and control applications in electrically noisy environments.",
    description: [
      "Braided Shielded Cable features a woven tinned copper braid surrounding the insulated conductors, providing superior electromagnetic interference (EMI) and radio frequency interference (RFI) shielding. This construction is essential for maintaining signal integrity in instrumentation, control, and data communication circuits operating in electrically noisy industrial environments.",
      "The braided shield construction offers 85-95% coverage depending on braid density, providing excellent shield effectiveness while maintaining cable flexibility. An overall PVC or thermoplastic elastomer jacket protects the braid from mechanical damage and environmental exposure, making these cables suitable for both fixed and flexible installations.",
    ],
    usage: [
      "Industrial instrumentation and process control",
      "Programmable logic controller (PLC) I/O wiring",
      "Variable frequency drive (VFD) motor leads",
      "Audio, video, and data communication circuits",
      "Medical and laboratory equipment wiring",
    ],
    features: [
      "Tinned copper braid shield (85-95% coverage)",
      "Superior EMI/RFI noise rejection",
      "Maintains signal integrity in noisy environments",
      "Flexible construction for routing in tight spaces",
      "Overall PVC or TPE outer jacket",
      "Available in multi-pair and multi-conductor configurations",
    ],
  },
];
