export interface TransformerProduct {
  slug: string;
  name: string;
  img: string;
  tags: string[];
  category: string;
  voltage: string;
  desc: string;
  description: string[];
  usage: string[];
  features: string[];
}

export const transformerProducts: TransformerProduct[] = [
  {
    slug: "dry-type-distribution-transformer",
    name: "Dry-Type Distribution Transformer",
    img: "/moonlights.github.io/assets/transformer_dry_type.png",
    tags: ["600V", "THREE-PHASE"],
    category: "Distribution",
    voltage: "600V",
    desc: "General purpose dry-type distribution transformer for stepping voltage up or down in commercial and industrial facilities. Air-cooled design eliminates fire risk.",
    description: [
      "Dry-type distribution transformers are the backbone of indoor power distribution for commercial buildings, industrial plants, hospitals, and data centers. Using air as the cooling medium instead of oil, these transformers eliminate the fire and environmental hazards associated with liquid-filled units, making them the preferred choice for indoor installations where safety is paramount.",
      "Available in three-phase configurations from 15 kVA to 2500 kVA, our dry-type distribution transformers feature copper or aluminum windings with Class H (180°C) insulation systems. They meet or exceed DOE 2016 efficiency standards and carry UL and CSA certifications. Common voltage configurations include 480V to 208Y/120V, 600V to 208Y/120V, and 480V to 240V delta.",
    ],
    usage: [
      "Commercial building main power distribution",
      "Industrial facility voltage step-down",
      "Hospital and healthcare critical power systems",
      "Data center power infrastructure",
      "Educational institution electrical systems",
    ],
    features: [
      "Air-cooled design — no oil, no fire risk",
      "Class H (180°C) insulation system",
      "DOE 2016 compliant energy efficiency",
      "Available 15 kVA through 2500 kVA",
      "NEMA 1, 2, 3R enclosure options",
      "UL Listed and CSA certified",
    ],
  },
  {
    slug: "control-transformer",
    name: "Industrial Control Transformer",
    img: "/moonlights.github.io/assets/transformer_control.png",
    tags: ["600V", "CONTROL"],
    category: "Control",
    voltage: "600V",
    desc: "Machine tool and control circuit transformer with superior voltage regulation. Handles high inrush currents from solenoids, contactors, and relays.",
    description: [
      "Industrial control transformers are specifically engineered to provide stable, regulated voltage for control circuits in machinery, automation systems, and industrial panels. Unlike standard transformers, control transformers are designed to handle the extreme inrush currents (up to 10x normal) generated when solenoids, contactors, and electromagnetic devices energize — maintaining secondary voltage within tight regulation limits.",
      "Our control transformers feature encapsulated or open-core construction with Class B or F insulation, available from 50 VA to 15 kVA. Primary voltages of 208V, 240V, 480V, and 600V step down to standard control voltages of 120V or 24V. Finger-safe terminal covers and DIN-rail mounting options streamline panel installation.",
    ],
    usage: [
      "Machine tool and CNC equipment control circuits",
      "Motor control center (MCC) control power",
      "PLC and automation panel power supply",
      "HVAC control system power",
      "Conveyor and material handling controls",
    ],
    features: [
      "Handles 10x inrush current without voltage collapse",
      "Encapsulated core for contaminant protection",
      "Finger-safe terminal covers standard",
      "Available 50 VA through 15 kVA",
      "DIN-rail and panel mount options",
      "Primary fuse protection included",
    ],
  },
  {
    slug: "isolation-transformer",
    name: "Isolation Transformer",
    img: "/moonlights.github.io/assets/transformer_isolation.png",
    tags: ["600V", "ISOLATED"],
    category: "Isolation",
    voltage: "600V",
    desc: "Galvanically isolated transformer providing complete electrical separation between primary and secondary circuits. Essential for sensitive equipment protection.",
    description: [
      "Isolation transformers provide complete galvanic separation between primary and secondary circuits, preventing the transfer of electrical noise, harmonics, DC components, and ground-loop currents. This electrical isolation is critical for protecting sensitive electronic equipment, medical devices, and instrumentation from power quality issues that can cause malfunction, data corruption, or equipment damage.",
      "Our isolation transformers feature electrostatic shielding between primary and secondary windings, providing up to 140 dB of common-mode noise rejection. Available in single-phase and three-phase configurations from 1 kVA to 1000 kVA, with primary and secondary voltages configurable to match any application requirement. Hospital-grade units meeting UL 1047 are available for medical applications.",
    ],
    usage: [
      "Sensitive electronic and IT equipment protection",
      "Medical and hospital-grade power systems",
      "Laboratory and test equipment power",
      "Telecommunications and broadcast facilities",
      "Industrial instrumentation power supply",
    ],
    features: [
      "Electrostatic shield — 140 dB noise rejection",
      "Complete galvanic isolation primary to secondary",
      "Hospital-grade UL 1047 units available",
      "Available 1 kVA through 1000 kVA",
      "Copper or aluminum windings",
      "Custom voltage configurations available",
    ],
  },
  {
    slug: "buck-boost-transformer",
    name: "Buck-Boost Transformer",
    img: "/moonlights.github.io/assets/transformer_buck_boost.png",
    tags: ["240V", "VOLTAGE CORRECTION"],
    category: "Buck-Boost",
    voltage: "240V",
    desc: "Compact autotransformer for correcting line voltage that is slightly above or below nominal. Economical solution for 5-20% voltage adjustment.",
    description: [
      "Buck-boost transformers are small, single-phase isolation transformers that are field-connected as autotransformers to raise (boost) or lower (buck) line voltage by small amounts — typically 5% to 20%. They provide an extremely cost-effective and compact solution when the available supply voltage is slightly above or below the voltage required by the connected equipment.",
      "Common applications include boosting 208V to 230V or 240V for motor and HVAC equipment, or bucking 240V down to 208V for lighting panels. Despite their small physical size, buck-boost transformers can handle loads from fractional kVA up to several hundred kVA when connected as autotransformers, since only a fraction of the total load passes through the transformer windings.",
    ],
    usage: [
      "Correcting low voltage for HVAC equipment",
      "Boosting 208V to 230V/240V for motors",
      "Bucking 240V to 208V for lighting systems",
      "Voltage correction for imported equipment",
      "Agricultural pump motor voltage adjustment",
    ],
    features: [
      "Extremely compact and cost-effective",
      "Field-configurable buck or boost connections",
      "Handles 5-20% voltage correction",
      "Available 50 VA through 10 kVA",
      "Four-wire connection for flexibility",
      "UL Listed and CSA certified",
    ],
  },
  {
    slug: "three-phase-autotransformer",
    name: "Three-Phase Autotransformer",
    img: "/moonlights.github.io/assets/transformer_auto_3ph.png",
    tags: ["600V", "THREE-PHASE"],
    category: "Auto",
    voltage: "600V",
    desc: "High-efficiency single-winding autotransformer for three-phase voltage conversion. More compact and economical than isolation transformers for non-isolated applications.",
    description: [
      "Three-phase autotransformers use a single shared winding per phase for both primary and secondary circuits, making them significantly more compact, lighter, and more efficient than equivalent two-winding isolation transformers. By transferring most of the power conductively rather than magnetically, autotransformers achieve efficiencies exceeding 98% — ideal for applications where electrical isolation is not required.",
      "Our three-phase autotransformers are available from 1 kVA to 1000 kVA with common configurations including 480V to 240V, 600V to 480V, and 240V to 208V. Open-frame and enclosed (NEMA 1, 3R, 4X) versions are available. They are widely used as step-down or step-up transformers in industrial power distribution, motor starting applications, and voltage matching between utility supply and equipment requirements.",
    ],
    usage: [
      "Industrial voltage step-down (600V to 480V, 480V to 240V)",
      "Reduced-voltage motor starting (soft start)",
      "Voltage matching for imported equipment",
      "Temporary power and construction site distribution",
      "Data center power conditioning",
    ],
    features: [
      "98%+ efficiency — minimal energy losses",
      "30-50% smaller and lighter than equivalent isolation units",
      "Available 1 kVA through 1000 kVA",
      "Open-frame and NEMA enclosed options",
      "Copper or aluminum windings",
      "Multiple voltage taps for field adjustment",
    ],
  },
  {
    slug: "drive-isolation-transformer",
    name: "Drive Isolation Transformer",
    img: "/moonlights.github.io/assets/transformer_drive_isolation.png",
    tags: ["600V", "VFD RATED"],
    category: "Isolation",
    voltage: "600V",
    desc: "Specialized transformer designed for variable frequency drive (VFD) applications. Handles harmonic distortion and non-linear loading from AC/DC motor drives.",
    description: [
      "Drive isolation transformers are purpose-built for the demanding electrical environment created by variable frequency drives (VFDs) and other non-linear electronic loads. Standard transformers can overheat and fail prematurely when subjected to the harmonic currents generated by VFD rectifier circuits. Drive isolation transformers address this with reinforced insulation, oversized conductors, and specially designed magnetic cores that tolerate high harmonic content without excessive heating.",
      "Our drive isolation transformers feature K-13 or K-20 rated designs with 200°C insulation systems, electrostatic shielding to reduce common-mode noise, and delta-wye configurations that trap third-order harmonics. Available from 3 kVA to 500 kVA, they are essential for protecting both upstream power systems and downstream drive electronics from the adverse effects of harmonic distortion.",
    ],
    usage: [
      "Variable frequency drive (VFD) power supply",
      "AC and DC motor drive isolation",
      "Industrial pump and fan speed control systems",
      "HVAC variable-speed compressor drives",
      "Elevator and crane motor drive applications",
    ],
    features: [
      "K-13/K-20 rated for harmonic environments",
      "200°C insulation system for thermal margin",
      "Electrostatic shield reduces common-mode noise",
      "Delta-wye traps 3rd-order harmonics",
      "Available 3 kVA through 500 kVA",
      "Forced-air cooling option for continuous heavy loads",
    ],
  },
  {
    slug: "step-down-distribution-transformer",
    name: "Step-Down Distribution Transformer",
    img: "/moonlights.github.io/assets/transformer_step_down.png",
    tags: ["600V", "STEP-DOWN"],
    category: "Distribution",
    voltage: "600V",
    desc: "Three-phase step-down transformer for converting high facility voltage to usable equipment voltage. The workhorse of commercial and industrial power distribution.",
    description: [
      "Step-down distribution transformers are the fundamental building block of electrical power distribution in commercial and industrial facilities. They convert higher utility supply voltages (typically 480V or 600V three-phase) to the lower voltages required by lighting, receptacles, and equipment — most commonly 208Y/120V for office and retail environments, or 240V delta for industrial machinery.",
      "Our step-down distribution transformers feature aluminum or copper windings with Class F or H insulation systems in ventilated NEMA 1 or weatherproof NEMA 3R enclosures. Available from 15 kVA to 2500 kVA, they meet DOE 2016 energy efficiency standards and include features such as multiple primary voltage taps (±2.5% and ±5%), 150°C thermal protection, and seismic certification options.",
    ],
    usage: [
      "480V to 208Y/120V for office buildings",
      "600V to 208Y/120V for Canadian facilities",
      "480V to 240V delta for industrial machinery",
      "Multi-floor commercial building distribution",
      "Retail and hospitality power distribution",
    ],
    features: [
      "Primary voltage taps: ±2.5% and ±5% FCAN/FCBN",
      "Class F or H insulation system",
      "DOE 2016 efficiency compliant",
      "Available 15 kVA through 2500 kVA",
      "150°C thermal overload protection",
      "Seismic certification available (IBC/CBC)",
    ],
  },
  {
    slug: "encapsulated-transformer",
    name: "Encapsulated Dry-Type Transformer",
    img: "/moonlights.github.io/assets/transformer_encapsulated.png",
    tags: ["600V", "SEALED"],
    category: "Distribution",
    voltage: "600V",
    desc: "Vacuum-pressure encapsulated transformer with epoxy-sealed core and coils. Maximum protection against moisture, dust, and contaminants in harsh environments.",
    description: [
      "Encapsulated dry-type transformers feature core and coil assemblies that are vacuum-pressure impregnated (VPI) and sealed in a protective epoxy resin coating. This process creates a solid, moisture-proof barrier around every conductor and insulation surface, making encapsulated transformers virtually immune to environmental contaminants — including moisture, dust, salt spray, chemicals, and industrial pollutants.",
      "These transformers are the go-to solution for harsh industrial environments where standard ventilated dry-type units would suffer accelerated insulation degradation. Available from 1 kVA to 500 kVA in single-phase and three-phase configurations, encapsulated transformers carry NEMA 4X ratings and are suitable for outdoor installations, marine applications, and food processing facilities where washdown capability is required.",
    ],
    usage: [
      "Chemical and petrochemical processing plants",
      "Food and beverage processing facilities",
      "Marine and offshore installations",
      "Outdoor and exposed location installations",
      "Wastewater treatment plant electrical systems",
    ],
    features: [
      "Vacuum-pressure epoxy encapsulation",
      "NEMA 4X / IP66 environmental protection",
      "Immune to moisture, dust, and chemicals",
      "Available 1 kVA through 500 kVA",
      "Marine and offshore grade options",
      "Self-extinguishing, non-toxic insulation",
    ],
  },
  {
    slug: "medium-voltage-transformer",
    name: "Medium Voltage Transformer",
    img: "/moonlights.github.io/assets/transformer_medium_voltage.png",
    tags: ["15kV", "PADMOUNT"],
    category: "Distribution",
    voltage: "15kV",
    desc: "Medium voltage liquid-filled padmount transformer for utility-to-facility power conversion. Converts distribution-level voltage to facility service voltage.",
    description: [
      "Medium voltage padmount transformers serve as the critical interface between the utility distribution network (typically 4.16kV to 34.5kV) and a facility's internal electrical system. Housed in tamper-resistant, compartmentalized enclosures, padmount transformers are designed for ground-level installation without the need for a fenced enclosure — making them ideal for commercial developments, campuses, and residential subdivisions.",
      "Our medium voltage transformers are liquid-filled (mineral oil or FR3 natural ester) for superior heat dissipation and are available from 75 kVA to 2500 kVA. They feature dead-front construction for enhanced personnel safety, bayonet fusing for overcurrent protection, and compartmentalized high-voltage and low-voltage sections. Options include reduced-flammable FR3 fluid, loop-feed capability, and SCADA-ready monitoring connections.",
    ],
    usage: [
      "Utility-to-facility primary power conversion",
      "Commercial development power distribution",
      "Campus and institutional power systems",
      "Renewable energy plant collection networks",
      "Underground distribution systems",
    ],
    features: [
      "Padmount compartmentalized enclosure",
      "Dead-front construction for personnel safety",
      "Available 75 kVA through 2500 kVA",
      "Mineral oil or FR3 natural ester fluid",
      "Bayonet fusing overcurrent protection",
      "Loop-feed and SCADA monitoring options",
    ],
  },
  {
    slug: "harmonic-mitigating-transformer",
    name: "K-Rated Harmonic Mitigating Transformer",
    img: "/moonlights.github.io/assets/transformer_harmonic.png",
    tags: ["480V", "K-RATED"],
    category: "Distribution",
    voltage: "480V",
    desc: "Specially designed K-rated transformer for non-linear loads. Cancels harmonic currents from computers, LED lighting, and electronic equipment to protect the electrical system.",
    description: [
      "K-rated harmonic mitigating transformers are specifically designed for the modern electrical environment where non-linear loads — computers, LED lighting, variable frequency drives, and switch-mode power supplies — generate significant harmonic currents. These harmonics cause overheating in standard transformers, leading to premature failure. K-rated transformers use oversized neutral conductors, specially designed cores, and phase-shifting winding configurations to safely handle these harmonics.",
      "Available in K-4, K-13, and K-20 ratings, our harmonic mitigating transformers feature zigzag secondary windings that cancel triplen (3rd, 9th, 15th) harmonics before they reach the upstream power system. This not only protects the transformer but also reduces neutral current, decreases voltage distortion, and improves overall power quality throughout the facility. Available from 15 kVA to 1000 kVA in three-phase configurations.",
    ],
    usage: [
      "Data center and server room power distribution",
      "Office buildings with high computer density",
      "LED lighting retrofit power distribution",
      "Broadcast and telecommunications facilities",
      "Medical imaging equipment power systems",
    ],
    features: [
      "K-4, K-13, K-20 harmonic handling ratings",
      "Zigzag winding cancels triplen harmonics",
      "200% rated neutral conductor",
      "Available 15 kVA through 1000 kVA",
      "Reduces system-wide voltage distortion (THD)",
      "DOE 2016 efficiency compliant",
    ],
  },
  {
    slug: "oil-filled-power-transformer",
    name: "Oil-Filled Power Transformer",
    img: "/moonlights.github.io/assets/transformer_medium_voltage.png",
    tags: ["34.5kV", "OIL-FILLED"],
    category: "Distribution",
    voltage: "34.5kV",
    desc: "High-capacity liquid-filled transformer designed for primary substations and heavy industrial applications.",
    description: [
      "Oil-filled power transformers are designed for high voltage and high power ratings where air cooling is insufficient. The mineral oil or natural ester fluid acts as both an electrical insulator and a highly effective cooling medium, allowing for compact designs at very high power levels.",
      "Available from 5 MVA up to 100 MVA, these substation-class transformers feature customizable impedance, load tap changers (LTC) for active voltage regulation, and comprehensive monitoring packages for dissolved gas analysis (DGA) and winding temperature."
    ],
    usage: [
      "Utility substations",
      "Heavy industrial plants (steel, mining, chemical)",
      "Renewable energy grid interconnections",
      "Data center primary power"
    ],
    features: [
      "High power density with liquid cooling",
      "Customizable impedance for short-circuit control",
      "Optional Load Tap Changers (LTC)",
      "Advanced SCADA monitoring packages",
      "Natural ester (FR3) fluid options"
    ],
  },
  {
    slug: "cast-resin-transformer",
    name: "Cast Resin Dry-Type Transformer",
    img: "/moonlights.github.io/assets/transformer_dry_type.png",
    tags: ["15kV", "CAST-RESIN"],
    category: "Distribution",
    voltage: "15kV",
    desc: "Medium voltage dry-type transformer with epoxy cast coils for maximum environmental and mechanical protection.",
    description: [
      "Cast resin transformers encase the high-voltage windings in a solid epoxy resin block under vacuum, providing exceptional mechanical strength and rendering the windings completely impervious to moisture, dust, and corrosive environments.",
      "These transformers offer the environmental robustness of liquid-filled units without the fire risk or maintenance requirements of oil. They are ideal for high-rise buildings, underground transit systems, and environmentally sensitive areas where oil spills cannot be tolerated."
    ],
    usage: [
      "High-rise commercial buildings",
      "Underground mining and transit systems",
      "Offshore oil and gas platforms",
      "Hospitals and critical care facilities"
    ],
    features: [
      "Zero fire risk and self-extinguishing",
      "Impervious to moisture and extreme pollution",
      "High short-circuit mechanical strength",
      "Minimal maintenance required",
      "Environmentally safe with no fluid leaks"
    ],
  },
  {
    slug: "single-phase-distribution-transformer",
    name: "Single-Phase Distribution Transformer",
    img: "/moonlights.github.io/assets/transformer_single_phase.png",
    tags: ["240V", "SINGLE-PHASE"],
    category: "Single-Phase",
    voltage: "240V",
    desc: "Single-phase dry-type transformer for light commercial and residential voltage step-down where three-phase power is not required.",
    description: [
      "Single-phase distribution transformers provide reliable voltage transformation for light commercial, residential, and small industrial loads served by single-phase power. They are the practical choice for stepping 480V or 240V down to 120/240V for receptacles, lighting, and appliance circuits in buildings without three-phase service.",
      "Available from 0.25 kVA to 167 kVA with copper or aluminum windings and Class H insulation, our single-phase units meet DOE 2016 efficiency standards and are offered in NEMA 1 indoor and NEMA 3R outdoor enclosures. Multiple primary taps allow field voltage adjustment to compensate for line variations.",
    ],
    usage: [
      "Light commercial 480V to 120/240V step-down",
      "Residential and farm voltage conversion",
      "Small shop and office power distribution",
      "Single-phase lighting and receptacle panels",
      "Well pump and agricultural equipment power",
    ],
    features: [
      "Single-phase 120/240V secondary configurations",
      "Class H (180°C) insulation system",
      "DOE 2016 efficiency compliant",
      "Available 0.25 kVA through 167 kVA",
      "NEMA 1 indoor and NEMA 3R outdoor options",
      "Multiple primary taps for field adjustment",
    ],
  },
  {
    slug: "low-voltage-lighting-transformer",
    name: "Low-Voltage Lighting Transformer",
    img: "/moonlights.github.io/assets/transformer_encapsulated.png",
    tags: ["120V", "12V/24V OUTPUT"],
    category: "Single-Phase",
    voltage: "240V",
    desc: "Magnetic low-voltage transformer for landscape, display, and architectural lighting requiring 12V or 24V output.",
    description: [
      "Low-voltage lighting transformers step standard line voltage down to 12V or 24V for landscape, display, cove, and architectural lighting systems. The magnetic (toroidal or laminated core) design delivers clean, stable low-voltage power that maximizes lamp life and supports long wire runs with minimal voltage drop.",
      "Our low-voltage lighting transformers are available from 60 VA to 1200 VA in weatherproof, stainless-steel, and encapsulated enclosures for indoor or outdoor installation. Multi-tap secondaries (11V–15V or 12V–22V) compensate for voltage drop on long landscape runs, and integral thermal/overload protection guards against faults.",
    ],
    usage: [
      "Landscape and outdoor pathway lighting",
      "Retail display and case lighting",
      "Cove and architectural accent lighting",
      "Under-cabinet and task lighting systems",
      "Halogen and low-voltage LED installations",
    ],
    features: [
      "12V and 24V secondary output options",
      "Multi-tap secondary for voltage-drop compensation",
      "Magnetic core for stable, clean output",
      "Available 60 VA through 1200 VA",
      "Weatherproof and stainless enclosures",
      "Integral thermal and overload protection",
    ],
  },
  {
    slug: "grounding-zigzag-transformer",
    name: "Zigzag Grounding Transformer",
    img: "/moonlights.github.io/assets/transformer_harmonic.png",
    tags: ["480V", "GROUNDING"],
    category: "Specialty",
    voltage: "480V",
    desc: "Zigzag-wound grounding transformer that derives a neutral point on ungrounded delta systems to provide a controlled ground reference.",
    description: [
      "Zigzag grounding transformers create an artificial neutral point on three-phase, three-wire (ungrounded delta) systems, enabling controlled system grounding without a separate power source. By providing a low-impedance path to ground for zero-sequence (fault) currents while presenting high impedance to balanced loads, they allow ground-fault detection and limit transient overvoltages.",
      "Our zigzag grounding transformers are designed for both solidly grounded and resistance-grounded applications and are available for systems from 480V through 15kV. Continuous and short-time (10-second/60-second) ground current ratings are specified to coordinate with system protection, and units are offered in dry-type and liquid-filled construction.",
    ],
    usage: [
      "Grounding ungrounded delta distribution systems",
      "Deriving a neutral for resistance grounding",
      "Industrial plant ground-fault detection",
      "Mining and generator system grounding",
      "Wind and solar collector system grounding",
    ],
    features: [
      "Derives neutral on three-wire delta systems",
      "Low zero-sequence, high positive-sequence impedance",
      "Continuous and short-time current ratings",
      "Available 480V through 15kV systems",
      "Dry-type and liquid-filled construction",
      "Coordinates with resistance grounding equipment",
    ],
  },
];
